import createClient, { type Client } from "openapi-fetch";
import { getAuthToken, loadConfig } from "../config";
import type { paths } from "../schema"; // generated by openapi-typescript

let __client: Client<paths, `${string}/${string}`> | undefined;

// TODO: eventually migrate all calls of 'apiClient' to 'useApi'
export const apiClient = async () => {
  if (__client) {
    return __client;
  }

  const config = await loadConfig();
  __client = createClient<paths>({
    baseUrl: config.api_url,
    headers: {
      Authorization: `Bearer ${await getAuthToken()}`,
      "Content-Type": "application/json",
    },
  });

  return __client;
};
