import { useState, useEffect } from "react";
import createClient, { type Client } from "openapi-fetch";
import { getAuthToken, loadConfig } from "../config";
import type { paths } from "../schema"; // generated by openapi-typescript
import type { Nullable } from "../helpers/empty";

export const useApi = () => {
  const [client, setClient] =
    useState<Nullable<Client<paths, `${string}/${string}`>>>(null);

  useEffect(() => {
    const initClient = async () => {
      const config = await loadConfig();
      const newClient = createClient<paths>({
        baseUrl: config.api_url,
        headers: {
          Authorization: `Bearer ${await getAuthToken()}`,
          "Content-Type": "application/json",
        },
      });

      setClient(newClient);
    };

    initClient();
  }, []);

  return {
    api: client,
    apiClientReady: !!client,
  };
};
