import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

export const apiClient = (url: string) => {
    return createClient<paths>({ baseUrl: url });
};