import createClient, { type Client } from "openapi-fetch";
import { getAuthToken, loadConfig } from "./helpers/config.ts";
import type { paths } from "./schema.ts"; // generated by openapi-typescript

let $client: Client<paths, `${string}/${string}`> | undefined;

export const apiClient = async (token?: string) => {
  if ($client) {
    return $client;
  }

  const config = await loadConfig();
  $client = createClient<paths>({
    baseUrl: config.api_url,
    headers: {
      Authorization: `Bearer ${token ?? (await getAuthToken())}`,
      "Content-Type": "application/json",
    },
  });

  return $client;
};
